services:
  - type: web
    name: verso-austral-spacy
    runtime: python
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python -m spacy download pt_core_news_lg && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    plan: free
